name: Release Package

on:
  push:
    branches:
      - master

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      id-token: write # required for trusted publishing to pypi
      contents: write # required for tag creation
    steps:
      - name: Check out the repository
        uses: actions/checkout@v5
        with:
            fetch-depth: 20

      - name: Setup PDM
        uses: pdm-project/setup-pdm@v4
        with:
          python-version: 3.9
          cache: true

      - name: Setup PDM bump plugin
        run: |
          pdm self add pdm-bump

      - name: Detect and tag new version
        id: check-version
        uses: salsify/action-detect-and-tag-new-version@v2.0.3
        with:
          version-command: |-
            pdm show --version


      - name: Bump version for developmental release
        if: "! steps.check-version.outputs.tag"
        run: |
          dev_version="$(echo $(pdm show --version).dev$(date +%s))"
          pdm bump to "$dev_version"

      - name: Install dependencies with PDM
        run: |
          pdm install

      - name: Build package
        run: |
          pdm build

      - name: Publish package on PyPI
        if: steps.check-version.outputs.tag
        uses: pypa/gh-action-pypi-publish@release/v1

      - name: Publish package on TestPyPI
        if: "! steps.check-version.outputs.tag"
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/